"""
IC Memo Generator — generates a Word document from due diligence results.
Bonus task: +5 points.

Requires: pip install python-docx
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import structlog

logger = structlog.get_logger()


@dataclass
class IcMemoConfig:
    """Configuration for IC memo generation."""

    firm_name: str = "PE Org-AI-R Partners"
    confidentiality: str = "CONFIDENTIAL — For Internal Use Only"
    output_dir: str = "./output/memos"


def _dimension_score_value(raw: Any) -> float:
    if raw is None:
        return 0.0
    if isinstance(raw, dict):
        return float(raw.get("score", 0) or 0)
    try:
        return float(raw)
    except (TypeError, ValueError):
        return 0.0


def _score_level_label(score: float) -> str:
    if score >= 80:
        return "L5 Excellent"
    if score >= 60:
        return "L4 Good"
    if score >= 40:
        return "L3 Adequate"
    if score >= 20:
        return "L2 Developing"
    return "L1 Nascent"


def _format_ci(ci: Any) -> str:
    if ci is None:
        return "—"
    if isinstance(ci, (list, tuple)) and len(ci) >= 2:
        return f"[{ci[0]}, {ci[1]}]"
    return str(ci)


def _title_case_dim(name: str) -> str:
    return name.replace("_", " ").title()


class IcMemoGenerator:
    """
    Generates a professional Word document IC memo from due diligence results.

    Uses the output of DueDiligenceState from the LangGraph workflow.

    generate_memo(state: dict, config: IcMemoConfig) -> str:
      Takes the completed DueDiligenceState dict and produces a .docx file.
      Returns the file path as a string.

    The Word document should have these sections:

    1. HEADER
       - Firm name (bold, large font, centered)
       - "INVESTMENT COMMITTEE MEMORANDUM" (centered)
       - Confidentiality notice (italic, centered)
       - Horizontal line

    2. DEAL INFORMATION TABLE
       A 2-column table with:
       - Company: {company_id}
       - Assessment Type: {assessment_type}
       - Requested By: {requested_by}
       - Date: today's date
       - Assessment Started: {started_at}
       - Assessment Completed: {completed_at}

    3. EXECUTIVE SUMMARY section
       Heading: "Executive Summary"
       Content:
       - Org-AI-R Score: {scoring_result["org_air"]} / 100
       - V^R Score: {scoring_result["vr_score"]}
       - H^R Score: {scoring_result["hr_score"]}
       - 95% CI: {scoring_result["confidence_interval"]}
       - HITL Required: {requires_approval}
       - Approval Status: {approval_status}

    4. DIMENSION SCORES section
       Heading: "AI Readiness by Dimension"
       A table with columns: Dimension | Score | Level
       Use scoring_result["dimension_scores"] dict.
       For each dimension, calculate level:
         score >= 80 → "L5 Excellent"
         score >= 60 → "L4 Good"
         score >= 40 → "L3 Adequate"
         score >= 20 → "L2 Developing"
         else        → "L1 Nascent"

    5. EVIDENCE JUSTIFICATIONS section
       Heading: "Evidence Justifications"
       For each dimension in evidence_justifications["justifications"]:
         Sub-heading: dimension name (title case)
         - Evidence Strength: {evidence_strength}
         - Rubric Match: {rubric_criteria}
         - Gaps: bullet list of gaps_identified

    6. VALUE CREATION PLAN section
       Heading: "Value Creation Plan"
       From value_creation_plan["gap_analysis"]:
       - Target Org-AI-R: {target_org_air}
       - Projected EBITDA Impact: {projected_ebitda_pct}%
       - Total Investment Estimate: ${total_investment_estimate:,}
       A table with columns: Dimension | Gap | Priority | Investment ($)
       from the gaps list.

    7. FOOTER
       "Generated by PE Org-AI-R Platform"
       datetime.now().strftime("%Y-%m-%d %H:%M:%S")
       Confidentiality notice.

    File naming: {company_id}_IC_Memo_{date}.docx
    Save to config.output_dir (create directory if it doesn't exist).
    Return the full file path.

    If python-docx is not installed, log an error and return empty string.
    Handle all missing keys with .get() and sensible defaults.
    """

    def __init__(self, config: Optional[IcMemoConfig] = None):
        self.config = config or IcMemoConfig()

    def generate_memo(
        self,
        state: Dict[str, Any],
        config: Optional[IcMemoConfig] = None,
    ) -> str:
        cfg = config or self.config
        try:
            from docx import Document
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.shared import Pt
        except ImportError:
            logger.error("python-docx not installed. Run: pip install python-docx")
            return ""

        doc = Document()
        company_id = state.get("company_id", "Unknown")
        scoring = state.get("scoring_result") or {}
        justifications_data = state.get("evidence_justifications") or {}
        justifications = justifications_data.get("justifications", {}) or {}
        value_plan = state.get("value_creation_plan") or {}
        gap_analysis = value_plan.get("gap_analysis") or {}

        # --- 1. HEADER ---
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(cfg.firm_name)
        r.bold = True
        r.font.size = Pt(18)

        p2 = doc.add_paragraph()
        p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r2 = p2.add_run("INVESTMENT COMMITTEE MEMORANDUM")
        r2.bold = True
        r2.font.size = Pt(14)

        p3 = doc.add_paragraph()
        p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r3 = p3.add_run(cfg.confidentiality)
        r3.italic = True
        r3.font.size = Pt(10)

        doc.add_paragraph("─" * 48)

        # --- 2. DEAL INFORMATION TABLE ---
        today_str = datetime.now().strftime("%Y-%m-%d")
        deal_rows = [
            ("Company", str(company_id)),
            ("Assessment Type", str(state.get("assessment_type", "—"))),
            ("Requested By", str(state.get("requested_by", "—"))),
            ("Date", today_str),
            ("Assessment Started", str(state.get("started_at", "—"))),
            ("Assessment Completed", str(state.get("completed_at", "—"))),
        ]
        tbl = doc.add_table(rows=len(deal_rows), cols=2)
        tbl.style = "Table Grid"
        for i, (label, val) in enumerate(deal_rows):
            tbl.rows[i].cells[0].text = label
            tbl.rows[i].cells[1].text = val

        doc.add_paragraph()

        # --- 3. EXECUTIVE SUMMARY ---
        doc.add_heading("Executive Summary", level=1)
        org_air = scoring.get("org_air", "—")
        vr = scoring.get("vr_score", "—")
        hr = scoring.get("hr_score", "—")
        ci = _format_ci(scoring.get("confidence_interval"))
        hitl = state.get("requires_approval", False)
        appr = state.get("approval_status", "—")
        doc.add_paragraph(f"Org-AI-R Score: {org_air} / 100")
        doc.add_paragraph(f"V^R Score: {vr}")
        doc.add_paragraph(f"H^R Score: {hr}")
        doc.add_paragraph(f"95% CI: {ci}")
        doc.add_paragraph(f"HITL Required: {hitl}")
        doc.add_paragraph(f"Approval Status: {appr}")
        if state.get("approval_reason"):
            doc.add_paragraph(f"Approval Reason: {state.get('approval_reason')}")
        if state.get("approved_by"):
            doc.add_paragraph(f"Approved By: {state.get('approved_by')}")

        # --- 4. DIMENSION SCORES ---
        doc.add_heading("AI Readiness by Dimension", level=1)
        dim_scores = scoring.get("dimension_scores") or {}
        if dim_scores:
            dt = doc.add_table(rows=1 + len(dim_scores), cols=3)
            dt.style = "Table Grid"
            hdr = dt.rows[0].cells
            hdr[0].text = "Dimension"
            hdr[1].text = "Score"
            hdr[2].text = "Level"
            for idx, (dim_name, raw) in enumerate(sorted(dim_scores.items()), start=1):
                sc = _dimension_score_value(raw)
                dt.rows[idx].cells[0].text = _title_case_dim(str(dim_name))
                dt.rows[idx].cells[1].text = f"{sc:.1f}"
                dt.rows[idx].cells[2].text = _score_level_label(sc)
        else:
            doc.add_paragraph("No dimension scores available.")

        # --- 5. EVIDENCE JUSTIFICATIONS ---
        doc.add_heading("Evidence Justifications", level=1)
        if not justifications:
            doc.add_paragraph("No evidence justifications available.")
        else:
            for dim_key, payload in sorted(justifications.items()):
                if not isinstance(payload, dict):
                    continue
                doc.add_heading(_title_case_dim(str(dim_key)), level=2)
                doc.add_paragraph(
                    f"Evidence Strength: {payload.get('evidence_strength', '—')}"
                )
                doc.add_paragraph(
                    f"Rubric Match: {payload.get('rubric_criteria', '—')}"
                )
                gaps = payload.get("gaps_identified") or []
                doc.add_paragraph("Gaps:")
                if isinstance(gaps, list) and gaps:
                    for g in gaps:
                        doc.add_paragraph(str(g), style="List Bullet")
                else:
                    doc.add_paragraph("—", style="List Bullet")

        # --- 6. VALUE CREATION PLAN ---
        doc.add_heading("Value Creation Plan", level=1)
        tgt = gap_analysis.get("target_org_air", "—")
        pebitda = gap_analysis.get("projected_ebitda_pct", "—")
        total_inv = gap_analysis.get("total_investment_estimate", 0)
        doc.add_paragraph(f"Target Org-AI-R: {tgt}")
        doc.add_paragraph(f"Projected EBITDA Impact: {pebitda}%")
        doc.add_paragraph(
            f"Total Investment Estimate: ${int(total_inv or 0):,}"
        )
        gaps_list: List[Dict[str, Any]] = gap_analysis.get("gaps") or []
        if gaps_list:
            gt = doc.add_table(rows=1 + len(gaps_list), cols=4)
            gt.style = "Table Grid"
            h = gt.rows[0].cells
            h[0].text = "Dimension"
            h[1].text = "Gap"
            h[2].text = "Priority"
            h[3].text = "Investment ($)"
            for i, g in enumerate(gaps_list, start=1):
                dim = str(g.get("dimension", "—"))
                gap_val = g.get("gap", "—")
                pri = str(g.get("priority", "—"))
                inv = g.get("investment_estimate", 0)
                gt.rows[i].cells[0].text = _title_case_dim(dim)
                gt.rows[i].cells[1].text = str(gap_val)
                gt.rows[i].cells[2].text = pri
                gt.rows[i].cells[3].text = f"{int(inv or 0):,}"
        else:
            doc.add_paragraph("No gap analysis rows available.")

        # --- 7. FOOTER ---
        doc.add_paragraph()
        doc.add_paragraph("─" * 48)
        fp = doc.add_paragraph()
        fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        fp.add_run("Generated by PE Org-AI-R Platform")
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        tp = doc.add_paragraph()
        tp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        tp.add_run(ts)
        cp = doc.add_paragraph()
        cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        cr = cp.add_run(cfg.confidentiality)
        cr.italic = True
        cr.font.size = Pt(9)

        # Save file
        output_path = Path(cfg.output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_company = "".join(c if c.isalnum() or c in "-_" else "_" for c in str(company_id))
        filename = f"{safe_company}_IC_Memo_{date_str}.docx"
        filepath = output_path / filename
        doc.save(str(filepath))
        logger.info("ic_memo_generated", path=str(filepath), company=company_id)
        return str(filepath)


ic_memo_generator = IcMemoGenerator()
