# src/services/search/vector_store.py
from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Dict, List, Optional

if TYPE_CHECKING:
    from src.services.retrieval.dimension_mapper import DimensionMapper

import chromadb
from chromadb.config import Settings
from sentence_transformers import SentenceTransformer

logger = logging.getLogger(__name__)

# batch size constant to avoid memory crash on large indexing jobs
ENCODE_BATCH_SIZE = 200


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class SearchResult:
    """A single result returned by VectorStore.search()."""
    doc_id: str
    content: str
    score: float          # cosine similarity 0.0 – 1.0 (higher = more similar)
    metadata: Dict[str, Any]


# ---------------------------------------------------------------------------
# VectorStore
# ---------------------------------------------------------------------------

class VectorStore:
    """
    ChromaDB-backed vector store preserving CS2 evidence metadata.

    Plain English flow:
        1. __init__      → open the filing cabinet, load the meaning translator
        2. index_*       → convert text → numbers → file with labels
        3. search()      → convert query → numbers → find closest matches

    Stores embeddings generated by SentenceTransformer (all-MiniLM-L6-v2)
    alongside rich metadata for filtered retrieval:
        company_id, source_type, signal_category, dimension,
        dimension_weights, confidence, fiscal_year, source_url
    """

    def __init__(self, persist_dir: str = "./chroma_data") -> None:
        # Open (or create) the persistent filing cabinet on disk
        self.client = chromadb.PersistentClient(
            path=persist_dir,
            settings=Settings(anonymized_telemetry=False),
        )
        # Get (or create) the "pe_evidence" drawer inside the cabinet
        # cosine = measure similarity by angle between vectors, not size
        self.collection = self.client.get_or_create_collection(
            name="pe_evidence",
            metadata={"hnsw:space": "cosine"},
        )
        # Load the meaning translator — converts text → 384 numbers
        self.encoder = SentenceTransformer("all-MiniLM-L6-v2")
        logger.info("vector_store_initialized", extra={"persist_dir": persist_dir})

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def index_cs2_evidence(
        self,
        evidence_list: List["CS2Evidence"],
        dimension_mapper: "DimensionMapper",
    ) -> int:
        """
        Index CS2Evidence objects into ChromaDB.

        Plain English:
            For each evidence item:
            1. Ask dimension_mapper: "what CS3 dimension does this belong to?"
            2. Attach that answer + all metadata as labels on the document
            3. Convert the text content into 384 numbers (the meaning vector)
            4. File it in ChromaDB with those numbers + labels

        Returns number of documents indexed.
        Upsert = safe to call multiple times, no duplicates created.
        """
        if not evidence_list:
            logger.warning("index_cs2_evidence_called_with_empty_list")
            return 0

        ids: List[str] = []
        contents: List[str] = []
        metadatas: List[Dict[str, Any]] = []

        for e in evidence_list:
            # Ask dimension mapper what CS3 dimension this signal belongs to
            dim_weights = dimension_mapper.get_dimension_weights(e.signal_category)
            primary_dim = dimension_mapper.get_primary_dimension(e.signal_category)

            ids.append(e.evidence_id)
            contents.append(e.content)
            metadatas.append({
                "company_id":        e.company_id,
                "source_type":       e.source_type.value,
                "signal_category":   e.signal_category.value,
                "dimension":         primary_dim.value,
                "dimension_weights": str(dim_weights),  # dict → string (ChromaDB requirement)
                "confidence":        e.confidence,
                "fiscal_year":       e.fiscal_year or 0,     # None not allowed in ChromaDB
                "source_url":        e.source_url or "",     # None not allowed in ChromaDB
            })

        # batch encoding to avoid memory crash on large evidence sets
        # Instead of encoding all 500 chunks at once, do 200 at a time
        return self._upsert_in_batches(ids, contents, metadatas)

    def index_documents(self, documents: List[Dict[str, Any]]) -> int:
        """
        Generic document indexing for analyst notes, DD findings, data room docs.

        Each document dict must have:
            doc_id:   str   — unique identifier
            content:  str   — the text to embed and search
            metadata: dict  — any labels to attach (company_id, dimension, etc.)

        Simpler than index_cs2_evidence because analyst notes skip the
        dimension mapper — the analyst specifies the dimension directly.
        """
        if not documents:
            return 0

        ids      = [d["doc_id"] for d in documents]
        contents = [d["content"] for d in documents]
        metadatas = [d.get("metadata", {}) for d in documents]

        # same batch safety for generic indexing
        return self._upsert_in_batches(ids, contents, metadatas)

    # ------------------------------------------------------------------
    # Search
    # ------------------------------------------------------------------

    def search(
        self,
        query: str,
        top_k: int = 10,
        company_id: Optional[str] = None,
        dimension: Optional[str] = None,
        source_types: Optional[List[str]] = None,
        min_confidence: float = 0.0,
    ) -> List[SearchResult]:
        """
        Semantic search with optional metadata filters.

        Plain English:
            1. Convert your query text into 384 numbers
            2. Find the top_k documents whose numbers are closest to yours
            3. Apply any label filters (company, dimension, confidence)
            4. Return ranked results, most similar first

        Args:
            query:          What you're looking for, in plain English.
            top_k:          How many results to return.
            company_id:     Only search within one company e.g. "NVDA".
            dimension:      Only search within one CS3 dimension
                            e.g. "data_infrastructure".
            source_types:   Only return specific source types
                            e.g. ["sec_10k_item_1", "job_posting_linkedin"].
            min_confidence: Only return evidence above this confidence level.
        """
        # define single_source BEFORE the if block
        # Bug fix — was causing NameError when source_types was None or length 1
        single_source: Optional[set] = None

        # Build ChromaDB filter labels (AND logic — all conditions must match)
        where: Dict[str, Any] = {}

        if company_id:
            where["company_id"] = company_id
        if dimension:
            where["dimension"] = dimension
        if min_confidence > 0.0:
            where["confidence"] = {"$gte": min_confidence}

        # ChromaDB handles single source_type natively via where clause
        # Multiple source_types must be filtered in Python after retrieval
        # because ChromaDB $in support is inconsistent across versions
        if source_types and len(source_types) == 1:
            where["source_type"] = source_types[0]
        elif source_types:
            single_source = set(source_types)   # will filter after retrieval

        chroma_where = self._build_where(where) if where else None

        # Convert query text → 384 numbers using the SAME model used at index time
        query_embedding = self.encoder.encode(query).tolist()

        # Over-fetch when post-filtering source_types so we still get top_k after filter
        n_results = top_k if single_source is None else top_k * 3

        # guard against empty collection crash
        # ChromaDB throws IndexError when collection is empty
        try:
            results = self.collection.query(
                query_embeddings=[query_embedding],
                n_results=n_results,
                where=chroma_where,
            )
        except Exception as exc:
            logger.warning("chroma_query_failed", extra={"error": str(exc)})
            return []

        # guard against empty results
        if not results["ids"] or not results["ids"][0]:
            return []

        # Convert ChromaDB output → SearchResult objects
        # ChromaDB returns distance (0=identical, 2=opposite)
        # We convert to similarity (1=identical, 0=opposite) with 1 - distance
        search_results = [
            SearchResult(
                doc_id=results["ids"][0][i],
                content=results["documents"][0][i],
                score=1 - results["distances"][0][i],
                metadata=results["metadatas"][0][i],
            )
            for i in range(len(results["ids"][0]))
        ]

        # Post-filter for multiple source_types
        if single_source:
            search_results = [
                r for r in search_results
                if r.metadata.get("source_type") in single_source
            ][:top_k]

        return search_results

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _upsert_in_batches(
        self,
        ids: List[str],
        contents: List[str],
        metadatas: List[Dict[str, Any]],
    ) -> int:
        """

        Plain English:
            Instead of converting all 500 chunks to numbers at once
            (which can crash with out-of-memory), do 200 at a time.
            Each batch is filed into ChromaDB before moving to the next.

        Returns total number of documents upserted.
        """
        total = 0
        for i in range(0, len(ids), ENCODE_BATCH_SIZE):
            batch_ids      = ids[i: i + ENCODE_BATCH_SIZE]
            batch_contents = contents[i: i + ENCODE_BATCH_SIZE]
            batch_meta     = metadatas[i: i + ENCODE_BATCH_SIZE]

            batch_embeddings = self.encoder.encode(batch_contents).tolist()

            self.collection.upsert(
                ids=batch_ids,
                embeddings=batch_embeddings,
                documents=batch_contents,
                metadatas=batch_meta,
            )
            total += len(batch_ids)
            logger.info(
                "batch_indexed",
                extra={"batch_start": i, "batch_size": len(batch_ids), "total_so_far": total},
            )

        return total

    @staticmethod
    def _build_where(conditions: Dict[str, Any]) -> Dict[str, Any]:
        """
        Build a ChromaDB where clause from a flat conditions dict.

        ChromaDB requires $and syntax when combining multiple filters.
        Single condition can be passed directly without wrapping.

        Examples:
            {"company_id": "NVDA"}
            → {"company_id": "NVDA"}   (single, no wrapping needed)

            {"company_id": "NVDA", "dimension": "talent"}
            → {"$and": [{"company_id": "NVDA"}, {"dimension": "talent"}]}
        """
        if len(conditions) == 1:
            return conditions
        return {"$and": [{k: v} for k, v in conditions.items()]}